# Binary "hosts" itself and doesn't need xinetd, so the jail doesn't work

FROM docker.io/rust:latest AS compile
COPY . /work
WORKDIR /work
RUN cargo build --release

FROM docker.io/debian:bullseye-slim AS app
# https://github.com/redpwn/jail
FROM localhost/challs/redjail:latest
COPY --from=app / /srv
COPY --from=compile /work/target/x86_64-unknown-linux-gnu/release/challenge /srv/app/run
RUN chmod -R 555 /srv/app/
ENV JAIL_MEM=20M JAIL_TIME=600 JAIL_CONNS_PER_IP=10 JAIL_PORT=2323
